"""empty message

Revision ID: 4d3109afbde0
Revises: 6760cb29d57e
Create Date: 2024-09-30 13:24:02.990519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d3109afbde0'
down_revision = '6760cb29d57e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('character_favorites_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'characters', ['character_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('character_favorites_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_column('character_id')

    # ### end Alembic commands ###
